name: Publish Release / Template

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish-release:
    uses: JSONbored/aio-fleet/.github/workflows/aio-publish-release.yml@aab4f9852ef6ead106f17d23d9400d627fd67dac
    permissions:
      actions: read
      contents: write
    with:
      release_name: Template
      component: ""
      workflow_selector: build.yml
    secrets: inherit
