name: Publish Release / Template

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish-release:
    uses: JSONbored/aio-fleet/.github/workflows/aio-publish-release.yml@a13769d03bb1eade5323709ea4d873874fb78cb2
    permissions:
      actions: read
      contents: write
    with:
      release_name: Template
      component: ""
      workflow_selector: build.yml
    secrets: inherit
