name: Publish Release / Template

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish-release:
    uses: JSONbored/aio-fleet/.github/workflows/aio-publish-release.yml@70792816d19763170bb5cce255a970e7fa2d45cf
    permissions:
      actions: read
      contents: write
    with:
      release_name: Template
      component: ""
      workflow_selector: build.yml
    secrets: inherit
