name: Prepare Release / Template

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  prepare-release:
    uses: JSONbored/aio-fleet/.github/workflows/aio-prepare-release.yml@ce6221adb01de3fbe16b40fa0274c950c1ccd225
    permissions:
      contents: write
      pull-requests: write
    with:
      release_name: Template
      component: ""
      component_label: ""
      previous_tag_command: latest-release-tag
    secrets: inherit
