name: Prepare Release / Template

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  prepare-release:
    uses: JSONbored/aio-fleet/.github/workflows/aio-prepare-release.yml@70792816d19763170bb5cce255a970e7fa2d45cf
    permissions:
      contents: write
      pull-requests: write
    with:
      release_name: Template
      component: ""
      component_label: ""
      previous_tag_command: latest-release-tag
    secrets: inherit
